all: c d

c:
	g++ -std=c++11  c.cpp -o c     ## basic format  map <string , map < string , vector < string , string , type>>>
 
d:
	g++ -std=c++11  d.cpp -o d		## advanced format map < argument , map < argument , vector < argument>>>    , argument is <string ,string , type>

clean:
	rm -rf c d
